### ISSUE TITLE
すでにブロックがある場所に空気を設定すると当たり判定が残っている

### ISSUE THREAD

**Issue by pasmophobia** [Be4rJP/Parallel#1]
すでにブロックが存在している場所にParallelWorld.setBlock(Material.AIR.createBlockData())を実行するとサーバー側に当たり判定が残ってしまう。

**Comment by bea4dev** [comment]
ParallelWorld.setBlockメソッドはチャンクに直接書き込まずプレイヤーに送信されるパケットを書き換えているためこのようなことが起こると推測されます。
解決策としてはあらかじめ何もないところにParallelWorld.setBlockで設置して必要になった時に後から書き換える方法があります。
また本来何もないところにプラグインからブロックを設置しその上にプレイヤーをしばらく乗せるとフライキックされる問題もあります。
この2つの問題を追々解決するための改善をする予定です。

**Comment by pasmophobia** [comment]
あざます
